# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
# instance_class: F2 - this is standard environment specific

env: flex

automatic_scaling:
  max_num_instances: 1